#!/bin/bash
#
# Builds "Dopamine Code.app" from source and signs it.
#
#   ./build.sh            build into ./build/Dopamine Code.app
#   ./build.sh --install  build, then replace /Applications/Dopamine Code.app and relaunch
#
# No Xcode project, no Developer account needed beyond the code-signing identity that is
# already in the login keychain. A locally built app carries no com.apple.quarantine
# attribute, so Gatekeeper never assesses it — there is no right-click-Open step.
#
set -euo pipefail

cd "$(dirname "$0")"

# The bundle carries the display name with its space; the executable and the source
# directory deliberately do not. A space in the executable name leaks into pgrep/pkill,
# launchctl labels and every shell glob that touches it.
APP_NAME="Dopamine Code"
EXECUTABLE="DopamineCode"
SRC_DIR="Sources/DopamineCode"
BUNDLE_ID="com.peter46jan.dopaminecode"
DEPLOYMENT_TARGET="13.0"
APP="build/$APP_NAME.app"

# TCC keys the Accessibility grant to the code signature. Signing with a real identity
# yields a designated requirement based on the bundle id and the certificate's common
# name, which stays constant across rebuilds. An ad-hoc signature is pinned to the
# cdhash instead, so every rebuild silently invalidates the grant.
SIGN_IDENTITY="${DOPAMINE_SIGN_IDENTITY:-Apple Development: <naam> (<team-id>)}"

say() { printf '\033[1m%s\033[0m\n' "$*"; }
warn() { printf '\033[33m%s\033[0m\n' "$*" >&2; }
die() { printf '\033[31m%s\033[0m\n' "$*" >&2; exit 1; }

# --- embed the privileged script ----------------------------------------------

# grant.sh runs as root. Handing the root shell a path under Contents/Resources would
# mean root executes whatever that file contains at the time — and the bundle lives in
# /Applications owned by the logged-in user, so any process running as that user could
# rewrite it and ride in on the admin password the user typed for something else.
#
# So the script text is compiled into the binary here. Resources/grant.sh stays the single
# source of truth and is also shipped in the bundle, readable, for running by hand.
GENERATED="$SRC_DIR/GrantScript.generated.swift"
say "Grant-script inbakken ($(wc -c < Resources/grant.sh | tr -d ' ') bytes)"
{
  echo "// Generated by build.sh from Resources/grant.sh. Do not edit."
  echo "//"
  echo "// Compiled in rather than read from disk at runtime: root must never execute a"
  echo "// file that an unprivileged process can rewrite between the prompt and the exec."
  echo "enum GrantScript {"
  printf '    static let base64 = "%s"\n' "$(base64 < Resources/grant.sh | tr -d '\n')"
  echo "}"
} > "$GENERATED"

# --- compile ------------------------------------------------------------------

say "Compileren ($(swiftc --version | head -1))"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

ARCH="$(uname -m)"
SOURCES=("$SRC_DIR"/*.swift)
[ ${#SOURCES[@]} -gt 0 ] || die "geen bronbestanden gevonden in $SRC_DIR"

swiftc \
  -O \
  -swift-version 5 \
  -parse-as-library \
  -target "${ARCH}-apple-macosx${DEPLOYMENT_TARGET}" \
  -framework SwiftUI -framework AppKit -framework IOKit \
  -framework Network -framework ServiceManagement -framework CoreGraphics \
  -framework UserNotifications \
  -o "$APP/Contents/MacOS/$EXECUTABLE" \
  "${SOURCES[@]}"

# --- assemble bundle ----------------------------------------------------------

cp Resources/Info.plist "$APP/Contents/Info.plist"
cp Resources/grant.sh "$APP/Contents/Resources/grant.sh"
chmod 0755 "$APP/Contents/Resources/grant.sh"
printf 'APPL????' > "$APP/Contents/PkgInfo"

# --- sign ---------------------------------------------------------------------

if security find-identity -v -p codesigning | grep -qF "$SIGN_IDENTITY"; then
  say "Ondertekenen met: $SIGN_IDENTITY"
  # --timestamp keeps the signature valid after the certificate expires.
  codesign --force --timestamp --options runtime \
           --identifier "$BUNDLE_ID" \
           -s "$SIGN_IDENTITY" "$APP" 2>&1 | sed 's/^/  /' || {
    warn "Ondertekenen met identiteit mislukt; val terug op ad-hoc."
    codesign --force --identifier "$BUNDLE_ID" -s - "$APP"
  }
else
  warn "Identiteit '$SIGN_IDENTITY' niet gevonden — ad-hoc ondertekenen."
  warn "Gevolg: de Toegankelijkheid-toestemming vervalt bij elke herbouw."
  codesign --force --identifier "$BUNDLE_ID" -s - "$APP"
fi

# A cdhash in the designated requirement means signing silently fell back to ad-hoc and
# the TCC grant is about to break on the next build.
DR="$(codesign -d -r- "$APP" 2>&1 | grep -i 'designated' || true)"
say "Designated requirement:"
printf '  %s\n' "$DR"
case "$DR" in
  *cdhash*) warn "Let op: cdhash-gebonden handtekening. Toestemmingen overleven een herbouw niet." ;;
esac

codesign --verify --deep --strict "$APP" && say "Handtekening geverifieerd."

# --- install ------------------------------------------------------------------

if [ "${1:-}" = "--install" ]; then
  DEST="/Applications/$APP_NAME.app"
  say "Installeren naar $DEST"

  # Quit the running copy, and the pre-rename one if it is still around. Waiting on the
  # process rather than sleeping a fixed second means we never delete a bundle out from
  # under a binary that is still executing from it.
  for name in "$EXECUTABLE" Wakker; do
    if pkill -x "$name" 2>/dev/null; then
      for _ in $(seq 1 40); do pgrep -x "$name" >/dev/null || break; sleep 0.25; done
      if pgrep -x "$name" >/dev/null; then
        warn "$name reageert niet op TERM; forceren."
        pkill -9 -x "$name" 2>/dev/null || true
        for _ in $(seq 1 20); do pgrep -x "$name" >/dev/null || break; sleep 0.25; done
        pgrep -x "$name" >/dev/null && die "$name draait nog; bundel niet vervangen."
      fi
    fi
  done

  rm -rf "$DEST"
  cp -R "$APP" "$DEST"

  # The old bundle would otherwise keep starting at login and fighting over the same
  # global kernel flag.
  if [ -d "/Applications/Wakker.app" ]; then
    warn "Oude /Applications/Wakker.app verwijderd."
    rm -rf "/Applications/Wakker.app"
  fi

  say "Starten"
  open "$DEST"
else
  say "Klaar: $APP"
  echo "Installeren met: ./build.sh --install"
fi
